language: ruby
cache: bundler
addons:
  ssh_known_hosts: ec2-54-68-27-245.us-west-2.compute.amazonaws.com
before_install:
- gem install bundler
- cp yamls/database.yml.travisCI config/database.yml
- mysql -e 'create database le_test;'
- mysql -e 'SET GLOBAL innodb_flush_log_at_trx_commit=2'
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1200x8"
bundler_args: "--without development production"
before_script:
- export DISPLAY=:99.0
- RAILS_ENV=test bundle exec rake db:migrate
- RAILS_ENV=test bundle exec rake db:test:prepare
script:
- RAILS_ENV=test bundle exec rspec spec
- RAILS_ENV=test bundle exec cucumber --profile travis
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
gemfile:
- Gemfile
branches:
  only:
  - master
  - patch
  - sprint
before_deploy:
- openssl aes-256-cbc -K $encrypted_59ed5570eba9_key -iv $encrypted_59ed5570eba9_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bundle install --without development production && bundle exec cap travisci deploy
  on:
    branch: sprint
    rvm: 1.9.3
notifications:
  slack:
    secure: LrIflpuuK/c+BBCviGD06sTHv9GuNB99Y2jJLFMb8CSxoHBuu9a8zkb8S40CuX0TKb6sRT6+vscgvVtFcN0hCi1LQZKhH/I01qr6rCEofkE+XlCxH1nbevSWGjMejvxlmHoMF9YT7+xauRa3rlEMAogeXTpGdICTGp83wi1ko1Y=
