<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip"
%>
default: <%= std_opts %> features
wip: --tags @wip:3 --wip features
travis: <%= std_opts %> features --tags ~@devOnly ~@selenium
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
alt_default: <%= std_opts %> --require config/environment.rb --require features/support/*.rb --require features/step_definitions --strict
